# NumPy Indexing and Selection

In [5]:
import numpy as np

In [2]:
arr = np.arange(1, 11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

9

In [5]:
arr[0:3]

array([1, 2, 3])

In [6]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# broadcast values in array
arr[:2] = 20

In [9]:
arr

array([20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(1, 11)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr2 = arr[0:6]

In [13]:
arr2

array([1, 2, 3, 4, 5, 6])

In [14]:
arr2[:]

array([1, 2, 3, 4, 5, 6])

In [15]:
arr2[:] = 100

In [16]:
arr2

array([100, 100, 100, 100, 100, 100])

In [17]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [18]:
arr = np.arange(1, 11)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# copy array in another variable
arr2 = arr.copy()

In [21]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr2[:] = 50

In [23]:
arr2

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Indexing 2-D array**

In [3]:
list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
arr_2d = np.array(list_1)

In [29]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr_2d[0]

array([1, 2, 3])

In [9]:
# array_name[row][column]
arr_2d[0][2]

3

In [16]:
arr_2d[1][1]

5

In [17]:
arr_2d[2][2]

9

In [18]:
arr_2d[2][1]

8

In [19]:
arr_2d[2][1] = 10

In [20]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 10,  9]])

In [21]:
# We can use comma also instead of two square brackets 
arr_2d[2,1]

10

In [22]:
arr_2d[1: , 1:]

array([[ 5,  6],
       [10,  9]])

In [23]:
arr_2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [26]:
arr = np.arange(0, 21)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [28]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [29]:
arr != 4

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [30]:
bool_array = arr <= 5

In [31]:
bool_array

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [33]:
# Get results only where is true.
arr[bool_array]

array([0, 1, 2, 3, 4, 5])

In [34]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])