# NumPy

NumPy is the linear algebra library for python.
It is importent in data science with python because, almost all the libraies in the PyData echosystem relay on NumPy as one of their one building block.

NumPy is also incredibly fast, as it has bindings to C libraries.

Install NumPy - pip install numpy

# NumPy Arrays

**NumPy arrays essentially come in two flavors :** Vector and Matrices.

Vectors are strictly 1-D arrays and matrices are 2-D arrays.

In [13]:
import numpy as np

**1-D Array**

In [5]:
my_list = [1, 2, 3, 4]

In [6]:
my_list

[1, 2, 3, 4]

In [7]:
arr = np.array(my_list)

In [14]:
arr

array([1, 2, 3, 4])

**2-D Array**

In [9]:
my_list2 = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]

In [10]:
my_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# It creates array of numbers. It works like range() function of python only the difference is it returns array.
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# It jumps in steps of 8.
np.arange(8, 81, 8)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [27]:
# It jumps in step of 2.
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# linspace returns 10 evenly spaced points from 0 to 10 in 1-D vector
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [31]:
# Identity matrix using numpy
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
# Random numbers array using numpy
# It creates array of the given shape uniformaly distributed from 0 to 1
# 1-D array of random numbers
np.random.rand(5)

array([0.90397098, 0.16948627, 0.31433758, 0.23237641, 0.39345274])

In [35]:
# 2-D array of random numbers
np.random.rand(5, 5)

array([[0.01282569, 0.50592736, 0.81165003, 0.68793379, 0.76054444],
       [0.61038922, 0.16430403, 0.29095981, 0.58102022, 0.6920507 ],
       [0.11347578, 0.80938823, 0.70642241, 0.988121  , 0.1371132 ],
       [0.81182014, 0.27314237, 0.32715909, 0.60167455, 0.47487693],
       [0.0934092 , 0.03631664, 0.34799756, 0.14132018, 0.26802836]])

In [36]:
# randn() returns numbers not from a uniform
np.random.randn(4)

array([ 0.8524846 , -0.31097227, -0.53723485,  0.81608408])

In [37]:
np.random.randn(3, 3)

array([[-0.76277952, -0.13519329,  0.79821377],
       [-1.21854977, -2.60847463, -0.54189022],
       [-3.20844553,  1.95647727,  0.98425405]])

In [39]:
# randint() returns a random integer from specified range
np.random.randint(1, 10)

6

In [41]:
# Third argument is for return more than one integer
np.random.randint(1, 100, 10)

array([19, 50, 88,  9, 46, 84, 19, 62, 12, 16])

# Methods of array

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr2 = np.random.randint(0, 50, 10)

In [47]:
arr2

array([45, 22, 10, 29, 25, 28, 24,  6, 19,  6])

In [56]:
# Array reshape method
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr2

array([45, 22, 10, 29, 25, 28, 24,  6, 19,  6])

In [58]:
# Find max value in array
arr.max()

24

In [59]:
arr2.max()

45

In [61]:
# Find min value in array
arr2.min()

6

In [62]:
# argmax() returns index location of max value
arr2.argmax()

0

In [63]:
# argmin() returns index location of min value
arr2.argmin()

7

In [65]:
# figure out shape of array
arr2.shape

(10,)

In [69]:
arr2 = arr2.reshape(2, 5)

In [70]:
arr2.shape

(2, 5)

In [71]:
arr2

array([[45, 22, 10, 29, 25],
       [28, 24,  6, 19,  6]])

In [72]:
# Get datatype of array
arr.dtype

dtype('int32')

In [73]:
arr2.dtype

dtype('int32')

In [78]:
arr3 = np.random.rand(3, 3)

In [79]:
arr3

array([[0.77780083, 0.57356597, 0.1704569 ],
       [0.9368011 , 0.74536652, 0.36463586],
       [0.82316113, 0.62412781, 0.52474621]])

In [81]:
arr3.dtype

dtype('float64')